name: Eleventy Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Node Packages
        run: npm ci

      - name: Build Website
        env:
          NOTION_API_KEY: '${{ secrets.NOTION_API_KEY }}'
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_dir: ./_site
